# Generated by Django 4.0.3 on 2022-06-08 00:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dr_created_at', models.DateTimeField()),
                ('dr_checked_at', models.DateTimeField(blank=True, null=True)),
                ('dr_status', models.CharField(choices=[('1', '결제대기'), ('2', '승인'), ('3', '반려')], max_length=10)),
                ('dr_title', models.CharField(max_length=100)),
                ('dr_feedback', models.CharField(blank=True, max_length=5000, null=True)),
                ('dr_addressee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addressee', to=settings.AUTH_USER_MODEL, verbose_name='승인자')),
                ('dr_drafter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafter', to=settings.AUTH_USER_MODEL, verbose_name='기안자')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '일일 보고',
                'verbose_name_plural': '일일 보고',
                'index_together': {('dr_drafter', 'dr_addressee')},
            },
        ),
        migrations.CreateModel(
            name='TommrowWill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tw_content', models.CharField(max_length=50, null=True)),
                ('tw_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document.dailyreport')),
            ],
            options={
                'verbose_name': '명일 업무 계획',
                'verbose_name_plural': '명일 업무 계획',
            },
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_content', models.CharField(max_length=50, null=True)),
                ('s_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document.dailyreport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '문제점 및 건의사항',
                'verbose_name_plural': '문제점 및 건의사항',
            },
        ),
        migrations.CreateModel(
            name='DailyContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dc_content', models.CharField(max_length=50, null=True)),
                ('dc_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document.dailyreport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '금일 업무 내용',
                'verbose_name_plural': '금일 업무 내용',
            },
        ),
    ]
