# Generated by Django 3.2.9 on 2022-05-31 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0003_auto_20220531_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='qna_hits',
            field=models.IntegerField(default=0, verbose_name='조회수'),
        ),
    ]
