# Generated by Django 3.2.9 on 2022-06-04 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0005_blog_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='question',
            name='qna_hits',
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
