# Generated by Django 4.0.4 on 2022-06-02 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_profile', models.ImageField(blank=True, upload_to='', verbose_name='프로필 사진')),
                ('user_department', models.CharField(blank=True, max_length=20, null=True, verbose_name='부서')),
            ],
        ),
    ]
