# Generated by Django 4.0.4 on 2022-06-03 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_profile',
        ),
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, upload_to='img', verbose_name='프로필 사진'),
        ),
    ]
