# Generated by Django 4.0.4 on 2022-06-03 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_remove_profile_user_profile_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, upload_to='static/img', verbose_name='프로필 사진'),
        ),
    ]
