# Generated by Django 4.0.4 on 2022-06-03 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_rename_user_profile_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='username',
            new_name='user',
        ),
    ]
