# Generated by Django 4.0.4 on 2022-06-03 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_rename_username_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, upload_to='profile/', verbose_name='프로필 사진'),
        ),
    ]
