# Generated by Django 2.1 on 2022-05-28 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commute_category', models.CharField(choices=[('1', '출근'), ('2', '퇴근'), ('3', '재택출근'), ('4', '재택퇴근')], max_length=1, verbose_name='출근/퇴근')),
                ('commute_date', models.DateTimeField(verbose_name='출퇴근시간')),
                ('commute_reason', models.CharField(max_length=500, null=True, verbose_name='재택사유')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
