# Generated by Django 2.1.5 on 2022-05-28 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commute', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='학번')),
            ],
        ),
    ]
