# Generated by Django 2.1.5 on 2022-05-28 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commute', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
