# Generated by Django 2.1.5 on 2022-05-29 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commute', '0009_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
