# Generated by Django 3.2.9 on 2022-05-31 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commute', '0010_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commute',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
