# Generated by Django 2.1.5 on 2022-05-29 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('board_title', models.CharField(max_length=100, null=True, verbose_name='게시판 제목')),
                ('board_content', models.TextField(max_length=500, null=True, verbose_name='내용')),
                ('board_date', models.DateTimeField(null=True, verbose_name='작성일')),
                ('board_hits', models.IntegerField(default=0, verbose_name='조회수')),
                ('board_file', models.FileField(blank=True, null=True, upload_to='', verbose_name='파일')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
        ),
    ]
